name: Epicgames Freebies Claimer
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * 2,4,6'

jobs:
  Claim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 14.x 
        uses: actions/setup-node@v1 
        with:
          node-version: "14.x"
                  
      - name: Run
        env:
          AUTH_JSON: ${{ secrets.AUTH_JSON }}
        run: |
          echo "$AUTH_JSON" | tr -d '\r' > $GITHUB_WORKSPACE/device_auths.json
          npm i 
          npm start
